version: '3'

services:
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: grajdolex
    ports:
      - 5555:3306
    volumes:
      - ./mysql:/var/lib/mysql
  wildfly:
    image: jboss/wildfly:18.0.0.Final
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - ./web/target:/opt/jboss/wildfly/standalone/deployments