<!DOCTYPE html>
<html lang="pl">
<#setting number_format="computer">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Informacje</title>
    <link rel="stylesheet" href="../css/rocket.css"/>
    <link rel="stylesheet" href="../css/info.css"/>
<body>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h1 align="center">Trochę o nas</h1>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h4>Jesteśmy grupą entuzjastów gier planszowych, którzy poznali się na kursie programowania. Zdecydowaliśmy się
            zrobić aplikację webową, która pozwoli na umawianie się na gry planszowe. Poniżej możesz zobaczyć jak
            wyglądamy.
            Radzimy żebyś zapamiętał te twarze, bo możliwe, że już wkrótce będą to najbardziej znane twarze w branży IT
            !</h4>
    </div>
    <div class="col-md-2"></div>
</div>
<br>
<div class="row" align="center">
    <div class="col-md-2"></div>

    <div class="team" align="center">
        <img src="../images/team.jpg" style="width: 1000px" align="center"/>
    </div>
    <div class="col-md-2"></div>

</div>

<h5>Dobrej zabawy!</h5>

</body>
</html>