<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Form</title>
    <link rel="stylesheet" href="../../css/rocket.css" />
    <link rel="stylesheet" href="../../css/info.css"/>
<body>
<h1>About us!</h1>
<div>
    <h4>We are group enthusiasts of board games who met on programming course.
        We decided to make a web application that allows create events for playing board games.
        Below you can see our faces and we are suggest you remember that faces because we
        will be the most famous pragmatists !</h4>

    <br>
    <div class="team">
        <img src="../../images/team.jpg" style="width: 1000px"/>
    </div>
    <h5>Enjoy!</h5>

</div>
</body>
</html>