<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" media="all" href="../../css/glowna/wydarzenia.css?v=3.034">
    <link rel="stylesheet" type="text/css" media="all" href="../../css/glowna/wydazeniabox.css">
    <link rel="stylesheet" type="text/css" media="all" href="../../css/glowna/fontWyda.css">

    <link rel="stylesheet" type="text/css" media="all" href="../../css/rocket.css">
    <link rel="stylesheet" href="../../css/fontello.css" />
    <link rel="stylesheet" href="../../css/kostka.css" />
    <link rel="stylesheet" href="../../https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="kubuś">

    <link href='../../css/glowna/fonntwydazzz.css' rel='stylesheet' type='text/css'>

    <title>Lista Wydarzen GrajDolex</title>




    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-32718192-1', 'auto');
        ga('send', 'pageview');

        setTimeout("ga('send','event','obecnosc','10s')",10000);
        setTimeout("ga('send','event','obecnosc','60s')",60000);
        setTimeout("ga('send','event','obecnosc','120s')",120000);
    </script>

    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MCG4KR7');</script>

    <script type="text/javascript">
        var _paq = _paq || [];
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
            var u="/Grajdolex/";
            _paq.push(['setTrackerUrl', u+'kiwi.php']);
            _paq.push(['setSiteId', '1']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'kiwi.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>

</head>


<body>


<noscript><iframe src="" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<header>
    <div id="perspektywa">
        <div id="rodzic">

            <div id="przod">
                <div></div>
            </div>

            <div id="tyl">
                <div></div>
                <div></div>
            </div>

            <div id="lewo">
                <div></div>
                <div></div>
                <div></div>
            </div>

            <div id="prawo">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>

            <div id="gora">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>

            <div id="dol">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>

        </div>
    </div>

    <div id="header-wraper">
        <div class="user-menu fr clearfix">
            <div class="lang">
                <a href="?changelang=en">en</a>
            </div>

            <div id="userbox" class="unlogged">
                <a href="javascript:void(0)" class="login-btn">Logowanie</a>
            </div>
            <div id="Grajdolex" class="userformbox">
                <h3 class="headline">Logowanie</h3>
                <div class="login-social-box">
                    <div class="login-label">przez Facebook:</div>
                    <a href="https://www.facebook.com"></a>
                    <span class="icon-loading anim"></span>
                    <div class="ff"></div>
                </div>
                <div class="login-label">przez adres e-mail:</div>
                <form method="post" action="/login">
                    <input type="text" class="txt required" name="email" placeholder="Twój e-mail" value="" />
                    <input type="password" class="txt required" name="password" placeholder="Hasło" value="" />
                    <a href="../zarejestruj-sie/" class="fl forgot">Nie masz konta?</a>
                    <a href="javascript:void(0)" class="fr forgot">Zapomniałem hasła</a>
                    <div class="ff"></div>
                    <span class="error"></span>
                    <div class="bottom">
                        <a href="javascript:void(0)" class="btn-cancel fl">Anuluj</a>
                        <input type="submit" class="submit fr" value="Zaloguj">
                        <span class="icon-loading fr anim"></span>
                        <div class="ff"></div>
                    </div>
                </form>
            </div>
            <div id="" class="userformbox">
                <h3 class="headline">Przypomnij hasło</h3>
                <img class="passwordbox-off" src="" alt="close" ></a>
                <span class="subheadline">
            Wypełnij formularz.<br />Na Twój adres e-mail zostanie wysłane link umożliwiający zmianę hasła.
        </span>
                <span class="error"></span>
                <span class="ok"></span>
                <form method="post" action="">
                    <input type="text" class="txt required" name="email" placeholder="Twój e-mail" value="" />
                    <a class="submit fr">Wyślij</a>
                    <span class="icon-loading fr anim"></span>
                    <div class="ff"></div>
                </form>
            </div>
        </div>
        <div class="brand fl">
            <a href="/">
                <img alt="" src="" >
            </a>
        </div>
        <div class="ff"></div>
        <nav class="clearfix">
            <div class="mobile-menu phoneOn">
                <img class="mobile-menu-on" src="" alt="mobile menu">
                <img class="mobile-menu-off" src="" alt="mobile menu close">
            </div>
            <ul class="main-menu">
                <li class="menu-item current"><a href="/wydarzenia/" onclick="ga('send', 'event', 'header', 'menu glowne', 'wydarzenia')">wydarzenia</a></li>
                <li class="menu-item"><a href="/orgazizacja/" onclick="ga('send', 'event', 'header', 'menu glowne')">orgazizacja</a></li>
                <li class="menu-item"><a href="/miejsca/" onclick="ga('send', 'event', 'header', 'menu glowne', 'cykle wydarzen')">miejsca</a></li>
                <li class="menu-item last"><a href="/blog/" onclick="ga('send', 'event', 'header', 'menu glowne', 'blog')">blog</a></li>
                <li class="menu-item desktopOff"><a href="/dodaj-wydarzenie/" onclick="ga('send', 'event', 'header', 'menu glowne', 'Dodaj wydarzenie')">Dodaj wydarzenie</a></li>
            </ul>
            <div id="top-searchbox">
                <a href="javascript:void(0)"></a>
                <div class="formbox">
                    <form action="/wyszukiwarka" method="get">
                        <fieldset>
                            <input type="text" name="fraza" placeholder="wpisz nazwę wydarzenia" autofocus />
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="add-menu tabletOff">
                Dodaj +                </div>
            <div class="add-menu-content">
                <a href="/dodaj-wydarzenie/" onclick="ga('send', 'event', 'header', 'menu dodaj +', 'Dodaj wydarzenie')">Wydarzenie</a>
            </div>
        </nav>
    </div>
</header>


<div id="container-form">
    <div class="content-form" id="cats-contentbox">
        <div class="clearfix">
            <div class="form-topicsbox form-box clearfix fl">
                <h3 class="fl">rodzaj:</h3>
                <div class="items fl">
                    <a href="javascript:void(0)" data-paramtype="event_categories" data-paramslug="Gry zręcznościowe" class="event_param active">akcji</a>
                    <a href="javascript:void(0)" data-paramtype="event_categories" data-paramslug="Gry logiczne" class="event_param ">logiczne</a>
                    <a href="javascript:void(0)" data-paramtype="event_categories" data-paramslug="Gry strategiczne" class="event_param ">strategiczne</a>
                </div>
            </div>
            <!--            <div>-->
            <!--                <select id="topicsselect2">-->
            <!--                    --><!--                        --><!--                        <option value=""></option>-->
            <!--                        --><!--                            --><!--                            --><!--                                <option value="--><!--">--><!--</option>-->
            <!--                            --><!--                        --><!--                    --><!--                </select>-->
            <!--            </div>-->
            <div class="form-city form-box clearfix fl">
                <h3 class="fl">Gdzie:</h3>
                <div class="items fl">
                    <a href="javascript:void(0)" data-paramtype="event_cities" data-paramslug="Gdansk" class="event_param ">Gdansk</a>
                    <a href="javascript:void(0)" data-paramtype="event_cities" data-paramslug="Sopot" class="event_param active">Sopot</a>
                    <a href="javascript:void(0)" data-paramtype="event_cities" data-paramslug="Gdynia" class="event_param ">Gdynia</a>
                    <a href="javascript:void(0)" data-paramtype="event_cities" data-paramslug="Poznan" class="event_param ">Poznań</a>
                    <a href="javascript:void(0)" data-paramtype="event_cities" data-paramslug="katowice" class="event_param ">Katowice</a>
                    <a href="javascript:void(0)" class="arrow-city">+</a>
                    <div class="ff"></div>
                    <div class="selectbox">
                        <input type="text" name="city_select" id="city_select" value="" autofocus placeholder="Wybierz miasto" />
                        <div class="items">
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="krakow">Kraków</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="warszawa">Warszawa</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="wroclaw">Wrocław</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="trojmiasto">Trójmiasto</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="poznan">Poznań</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="katowice">Katowice</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="lodz">Łódź</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="bialystok">Białystok</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="szczecin">Szczecin</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="torun">Toruń</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="lublin">Lublin</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="rzeszow">Rzeszów</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="gliwice">Gliwice</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="olsztyn">Olsztyn</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="bydgoszcz">Bydgoszcz</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="kielce">Kielce</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="online">On-line</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="czestochowa">Częstochowa</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="bielskobiala">Bielsko Biała</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="opole">Opole</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="zielonagora">Zielona Góra</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="radom">Radom</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="rawamazowiecka">Rawa Mazowiecka</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="szczyrk">Szczyrk</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="koszalin">Koszalin</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="tarnow">Tarnów</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="bialapodlaska">Biała Podlaska</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="plock">Płock</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="puck">Puck</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="bochnia">Bochnia</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="zabrze">Zabrze</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="przemysl">Przemyśl</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="siedlce">Siedlce</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="leszno">Leszno</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="suwalki">Suwałki</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="maslow">Masłów</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="wetlina">Wetlina</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="raclawice">Racławice</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="sosnowiec">Sosnowiec</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="krosno">Krosno</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="zakopane">Zakopane</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="swinoujscie">Świnoujście</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="trzebieszowice">Trzebieszowice</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="gorakalwaria">Góra Kalwaria</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="nowysacz">Nowy Sącz</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="hucisko">Hucisko</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="wisla">Wisła</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="plonsk">Płońsk</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="swidnica">Świdnica</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="jawor">Jawor</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="gorzowwielkopolski">Gorzów Wielkopolski</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="chelm">Chełm</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="karpacz">Karpacz</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="raciborz">Racibórz</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="dabrowagornicza">Dąbrowa Górnicza</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="wodzislawslaski">Wodzisław Śląski</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="piotrkowtrybunalski">Piotrków Trybunalski</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="kalisz">Kalisz</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="wloclawek">Włocławek</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="rybnik">Rybnik</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="ustron">Ustroń</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="tychy">Tychy</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="chorzow">Chorzów</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="radzymin">Radzymin</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="pulawy">Puławy</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="ostroda">Ostróda</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="zary">Żary</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="krynica-zdroj">Krynica Zdrój</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="zawiercie">Zawiercie</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="olkus">kusz</div>
                            <div class="item event_param" data-paramtype="event_cities" data-paramslug="bukowina-tatrzanska">Bukowina Tatrzańska</div>
                        </div>
                    </div>

                </div>
            </div>
            <a href="javascript:void(0)" class="fr" id="btn-showtopics">Więcej</a>
        </div>
        <div class="topics-listbox form-box clearfix active">
            <h3 class="fl">Tematy</h3>
            <div class="topics-items fl clearfix">
                <div class="selectbox fl">
                    <input type="text" name="topics_select" id="topics_select" placeholder="Jakich tematów szukasz?" />
                    <div class="items-special">
                        <div class="item event_param" data-paramtype="event_topics" data-paramslug="gry">gry</div>
                    </div>
                    <div class="items">
                        <div class="item event_param" data-paramtype="event_topics" data-paramslug="Gry">Gry</div>
                    </div>
                </div>
                <a href="javascript:void(0)" data-paramtype="event_topics" data-paramslug="Szukaj" class="event_param active">Szukaj</a>
            </div>

        </div>
    </div>
</div>

<div id="container" class="event-list">
    <div class="fr" id="btn-favlist">
        Stwórz swoją listę wydarzeń
        (<span>0</span>)
        <div class="items">
                <span class="info">

                    Zaloguj się aby utworzyć tu swoją listę wydarzeń. <a href="" target="_blank">Dowiedz się więcej</a>

                </span>
        </div>
    </div>

    <h1 class="clearfix"><div class="fl">Nadchodzące<span class="phoneOff"> wydarzenia</span>:</div>
        <a href="javascript:void(0)" id="btn-addnew-favlist" class="fl " title="Dodaj do moich list wydarzeń" data-userlogged=""></a>
        <input type="hidden" value="events" name="listtype" />
        <input type="hidden" value="Gdańsk" name="listslug" />
    </h1>
    <div class="popupbox" data-type="favlist-popupbox">
        <div class="add">
            Lista została zapisana w moich listach wydarzeń
        </div>
        <div class="cancel">Lista została usunięta z moich list wydarzeń</div>
    </div>

    <div class="ff"></div>
    <div class="event-list clearfix ">
        <div class="empty-list">Lista Wydarzen <br />
            Wiesz o jakimś wydarzeniu? <a href="/dodaj-wydarzenie/">Dodaj Wydarzeie</a></div>
    </div>
    <div class="ff"></div>
    <div class="event-list clearfix old">
        <h2 class="clearfix"><div class="fl">Minione wydarzenia:</div> <span class="number ">
            <div class="fl cat-item">Gdansk</div>
            <i class="fa fa-circle fl" aria-hidden="true"></i>
            <div class="fl cat-item">Gry</div>
        <div class="ff"></div>
        <div class="monthsbox clearfix">
            <div class="month-leftbox fl">
                <div class="col-monthbox">
                    <div>Listopad</div>
                    2020 </div>
            </div>
            <div class="list fl">
                <div class="tab-row">
                    <a class="clearfix" href="">
                        <div class="colTab date">
                            <div>
                                <div class="first clearfix"><div class="num fl">06.11</div><div class="name fl">Śr</div></div>
                            </div>
                        </div>
                        <div class="colTab title">sopot
                            <div class="topics">
                            <span class="fl"></span>
                            <i class="fa fa-circle fl" aria-hidden="true"></i>
                            gra</div>
                        </div>
                        <div class="colTab city">
                            Sopot</div>
                        <div class="colTab type">
                            Spotkanie</div>
                        <div class="colTab cost">

                            ilość 2-6
                        </div>
                    </a>
                </div>

            </div>
        </div>

        <div class="monthsbox clearfix">
            <div class="month-leftbox fl">
                <div class="col-monthbox">
                    <div>Wrzesień</div>
                    2019</div>
            </div>
            <div class="list fl">
                <div class="tab-row">
                    <a class="clearfix" href="/wydarzenia/dev-js-warszawa-11-wrzesien-2019">
                        <div class="colTab date">
                            <div>
                                <div class="first clearfix"><div class="num fl">25.09</div><div class="name fl">Śr</div></div>
                            </div>


                        </div>
                        <div class="colTab title">
                            dev<div class="topics">
                            <span class="fl"></span>
                            <i class="fa fa-circle fl" aria-hidden="true"></i>
                            Granie</div>
                        </div>
                        <div class="colTab city">Gdynia</div>
                        <div class="colTab type">
                            Spotkanie</div>
                        <div class="colTab cost">

                            ilość 2-6

                        </div>
                    </a>
                </div>

            </div>
        </div>

        <div class="monthsbox clearfix">
            <div class="month-leftbox fl">
                <div class="col-monthbox">
                    <div>Kwiecień</div>
                    2019</div>
            </div>
            <div class="list fl">
                <div class="tab-row">
                    <a class="clearfix" href="/wydarzenia/gamedev-js-warszawa-11-z-meet-js">
                        <div class="colTab date">
                            <div>
                                <div class="first clearfix"><div class="num fl">25.04</div><div class="name fl">Czw</div></div>
                            </div>


                        </div>
                        <div class="colTab title">
                            Game<div class="topics">
                            <span class="fl"></span>
                            <i class="fa fa-circle fl" aria-hidden="true"></i>
                            Granie</div>
                        </div>
                        <div class="colTab city">
                            Gdańsk</div>
                        <div class="colTab type">
                            Spotkanie</div>
                        <div class="colTab cost">

                            ilość 2-5

                        </div>
                    </a>
                </div>

            </div>
        </div>

        <div class="monthsbox clearfix">
            <div class="month-leftbox fl">
                <div class="col-monthbox">
                    <div>Marzec</div>2019</div>
            </div>
            <div class="list fl">
                <div class="tab-row">
                    <a class="clearfix" href="/wydarzenia/gamedev-js-warszawa-10-podczas-wdi-2019">
                        <div class="colTab date">
                            <div>
                                <div class="first clearfix"><div class="num fl">26.03</div><div class="name fl">Wt</div></div>
                            </div>


                        </div>
                        <div class="colTab title">
                            Granie<div class="topics">

                            <span class="fl"></span>
                            <i class="fa fa-circle fl" aria-hidden="true"></i>
                            lol</div>
                        </div>
                        <div class="colTab city">
                            Gdańsk</div>
                        <div class="colTab type">
                            Spotkanie</div>
                        <div class="colTab cost">
                            ilość 2-4

                        </div>
                    </a>
                </div>

            </div>
        </div>

        <div class="monthsbox clearfix">
            <div class="month-leftbox fl">
                <div class="col-monthbox">
                    <div>Styczeń</div>
                    2019</div>
            </div>
            <div class="list fl">
                <div class="tab-row">
                    <a class="clearfix" href="/wydarzenia/gamejam-js-2019">
                        <div class="colTab date">
                            <div>
                                <div class="first clearfix"><div class="num fl">25.01</div><div class="name fl">Pt</div></div>
                                <div class="second clearfix"><div class="num fl">- 27.01</div><div class="name fl">Nd</div></div>
                            </div>
                        </div>
                        <div class="colTab title">
                            Game<div class="topics">
                            <span class="fl"></span>
                            <i class="fa fa-circle fl" aria-hidden="true"></i>
                            granie</div>
                        </div>
                        <div class="colTab city">
                            Gdańsk</div>
                        <div class="colTab type">
                            Spotkanie</div>
                        <div class="colTab cost">

                            ilość 2-10

                        </div>
                    </a>
                </div>

            </div>
        </div>

        <div class="monthsbox clearfix">
            <div class="month-leftbox fl">
                <div class="col-monthbox">
                    <div>Grudzień</div>2018</div>
            </div>
            <div class="list fl">
                <div class="tab-row">
                    <a class="clearfix" href="/wydarzenia/2018">
                        <div class="colTab date">
                            <div>
                                <div class="first clearfix"><div class="num fl">04.12</div><div class="name fl">Wt</div></div>
                                <div class="second clearfix"><div class="num fl">- 05.12</div><div class="name fl">Śr</div></div>
                            </div>


                        </div>
                        <div class="colTab title">
                            Rozwijaj się<div class="topics">
                            <span class="fl"></span>
                            <i class="fa fa-circle fl" aria-hidden="true"></i>
                            Gry Strategiczne</div>
                        </div>
                        <div class="colTab city">Gdańsk</div>
                        <div class="colTab type">pub</div>
                        <div class="colTab cost">
                            Ilość 2-6

                        </div>
                    </a>
                </div>

            </div>

    </div>
    <a href="" class="button right button-heading show-archive">Przejdź do archiwum wydarzeń</a>
    <div class="legend">
        <strong>Legenda:</strong>
        <div><span class="special spons"> Z </span>&nbsp;- wydarzenie Zajete</div>
        <div><span class="special new"> Nowe </span>&nbsp;- wydarzenie dodane w ciągu ostatnich 7 dni</div>
    </div>
</div>

        <div class="content">


            <div class="socials">
                <div class="socialdivs">
                    <div class="fb">
                        <i class="icon-facebook"></i>
                    </div>
                    <div class="yt">
                        <i class="icon-youtube"></i>
                    </div>
                    <div class="tw">
                        <i class="icon-twitter"></i>
                    </div>
                    <div class="gplus">
                        <i class="icon-gplus"></i>
                    </div>
                    <div style="clear:both"></div>
                </div>
            </div>

        </div>
        <div class="clear"></div>
</div>

<script type="text/javascript">
    getPartCook();
</script>
<script src="jquery-1.11.3.min.js"></script>

<script>

    $(document).ready(function() {
        var NavY = $('.nav').offset().top;

        var stickyNav = function(){
            var ScrollY = $(window).scrollTop();

            if (ScrollY > NavY) {
                $('.nav').addClass('sticky');
            } else {
                $('.nav').removeClass('sticky');
            }
        };

        stickyNav();

        $(window).scroll(function() {
            stickyNav();
        });
    });

</script>
<style>
    #perspektywa {
        width:100px;
        height:100px;
        margin:0 auto;
        perspective:300px;
        -webkit-perspective:300px;
    }

    #rodzic {
        width:100%;
        height:100%;
        position:relative;
        transform-style:preserve-3d;
        -webkit-transform-style:preserve-3d;
        animation:obrot 4s linear infinite;
        -webkit-animation:obrot 4s linear infinite;
    }

    #rodzic > div {
        width:100%;
        height:100%;
        position:absolute;
        background-image:radial-gradient(ellipse at center,rgba(0,0,255,0.8),rgba(0,0,0,0.8));
        box-shadow:0 0 4px #00F;
    }

    #przod {
        transform:translateZ(50px);
        -webkit-transform:translateZ(50px);
    }

    #tyl {
        transform:translateZ(-50px);
        -webkit-transform:translateZ(-50px);
    }

    #lewo {
        transform:rotateY(-90deg) translateZ(50px);
        -webkit-transform:rotateY(-90deg) translateZ(50px);
    }

    #prawo {
        transform:rotateY(90deg) translateZ(50px);
        -webkit-transform:rotateY(90deg) translateZ(50px);
    }

    #gora {
        transform:rotateX(-90deg) translateZ(50px);
        -webkit-transform:rotateX(-90deg) translateZ(50px);
    }

    #dol {
        transform:rotateX(90deg) translateZ(50px);
        -webkit-transform:rotateX(90deg) translateZ(50px);
    }

    #rodzic > div > div {
        position:absolute;
        width:20px;
        height:20px;
        background-color:#FFF;
        border-radius:25%;
        box-shadow:0 0 4px 2px #000, 0 0 3px 1px #00F inset;
    }

    #przod > div:nth-child(1) { left:40px; top:40px; }

    #tyl > div:nth-child(1) { left:10px; top:10px; }
    #tyl > div:nth-child(2) { left:70px; bottom:10px; }

    #lewo > div:nth-child(1) { left:10px; top:10px; }
    #lewo > div:nth-child(2) { left:40px; top:40px; }
    #lewo > div:nth-child(3) { left:70px; bottom:10px; }

    #prawo > div:nth-child(1) { left:10px; top:10px; }
    #prawo > div:nth-child(2) { left:70px; top:10px; }
    #prawo > div:nth-child(3) { left:70px; bottom:10px; }
    #prawo > div:nth-child(4) { left:10px; bottom:10px; }

    #gora > div:nth-child(1) { left:10px; top:10px; }
    #gora > div:nth-child(2) { left:70px; top:10px; }
    #gora > div:nth-child(3) { left:70px; bottom:10px; }
    #gora > div:nth-child(4) { left:10px; bottom:10px; }
    #gora > div:nth-child(5) { left:40px; top:40px; }

    #dol > div:nth-child(1) { left:10px; top:10px; }
    #dol > div:nth-child(2) { left:70px; top:10px; }
    #dol > div:nth-child(3) { left:10px; top:40px; }
    #dol > div:nth-child(4) { left:70px; top:40px; }
    #dol > div:nth-child(5) { left:70px; bottom:10px; }
    #dol > div:nth-child(6) { left:10px; bottom:10px; }

    @keyframes obrot
    {
        0% { transform:rotateX(0) rotateZ(0); }
        100% { transform:rotateX(360deg) rotateZ(360deg); }
    }

    @-webkit-keyframes obrot
    {
        0% { -webkit-transform:rotateX(0) rotateZ(0); }
        100% { -webkit-transform:rotateX(360deg) rotateZ(360deg); }
    }
</style>
</body>
</html>